// mbflow-ui/src/components/nodes/config/TelegramParseNodeConfig.vue
<template>
  <div class="telegram-parse-config space-y-4">
    <!-- Extraction Options -->
    <div class="space-y-4">
      <h4 class="text-xs font-semibold uppercase text-gray-500">
        Extraction Settings
      </h4>

      <div class="flex flex-col gap-3">
        <Checkbox
          :model-value="localConfig.extract_files ?? true"
          @update:model-value="localConfig.extract_files = $event"
          label="Extract Files"
        />
        <p class="ml-6 -mt-2 text-xs text-gray-500">
          Extract photo, document, audio, video files from messages
        </p>

        <Checkbox
          :model-value="localConfig.extract_commands ?? true"
          @update:model-value="localConfig.extract_commands = $event"
          label="Extract Commands"
        />
        <p class="ml-6 -mt-2 text-xs text-gray-500">
          Parse /commands and extract arguments
        </p>

        <Checkbox
          :model-value="localConfig.extract_entities ?? false"
          @update:model-value="localConfig.extract_entities = $event"
          label="Extract Entities"
        />
        <p class="ml-6 -mt-2 text-xs text-gray-500">
          Extract URLs, emails, and @mentions from text
        </p>
      </div>
    </div>

    <!-- Output Info -->
    <div class="rounded-md bg-blue-50 p-3">
      <h5 class="text-xs font-medium text-blue-800">Output Fields</h5>
      <ul class="mt-1 text-xs text-blue-700 list-disc list-inside space-y-0.5">
        <li><code>update_type</code> - message, callback_query, etc.</li>
        <li><code>message_type</code> - text, photo, document, etc.</li>
        <li><code>text</code> - message text or caption</li>
        <li><code>command</code> - extracted command (if enabled)</li>
        <li><code>files</code> - array of file info (if enabled)</li>
        <li><code>user</code> - sender information</li>
        <li><code>chat</code> - chat/group information</li>
      </ul>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from "vue";
import Checkbox from "@/components/ui/Checkbox.vue";
import type { TelegramParseNodeConfig } from "@/types/nodes";

const props = defineProps<{
  config: TelegramParseNodeConfig;
  nodeId: string;
}>();

const emit = defineEmits<{
  (e: "update:config", config: TelegramParseNodeConfig): void;
}>();

const localConfig = ref<TelegramParseNodeConfig>({
  ...props.config,
  extract_files: props.config.extract_files ?? true,
  extract_commands: props.config.extract_commands ?? true,
  extract_entities: props.config.extract_entities ?? false,
});

watch(
  localConfig,
  (newConfig) => {
    emit("update:config", { ...newConfig });
  },
  { deep: true }
);

watch(
  () => props.config,
  (newConfig) => {
    if (JSON.stringify(newConfig) !== JSON.stringify(localConfig.value)) {
      localConfig.value = { ...localConfig.value, ...newConfig };
    }
  },
  { deep: true }
);
</script>

// ui/components/nodes/config/TelegramParseNodeConfig.tsx
/**
 * TelegramParseNodeConfig - React component for configuring Telegram parse nodes
 *
 * Features:
 * - Extract files option: checkbox
 * - Extract commands option: checkbox
 * - Extract entities option: checkbox
 *
 * Usage:
 * ```tsx
 * <TelegramParseNodeConfigComponent
 *   config={parseConfig}
 *   nodeId="node-123"
 *   onChange={(newConfig) => updateNode(newConfig)}
 * />
 * ```
 */

import React, {useEffect, useState} from 'react';
import {TelegramParseNodeConfig} from '@/types/nodeConfigs.ts';
import { useTranslation } from '@/store/translations';

interface TelegramParseNodeConfigProps {
    config: TelegramParseNodeConfig;
    nodeId?: string;
    onChange: (config: TelegramParseNodeConfig) => void;
}

export const TelegramParseNodeConfigComponent: React.FC<
    TelegramParseNodeConfigProps
> = ({config, nodeId, onChange}) => {
    const t = useTranslation();
    const [localConfig, setLocalConfig] = useState<TelegramParseNodeConfig>({
        extract_files: config.extract_files ?? true,
        extract_commands: config.extract_commands ?? true,
        extract_entities: config.extract_entities ?? false,
    });

    useEffect(() => {
        const newConfig: TelegramParseNodeConfig = {
            extract_files: config.extract_files ?? true,
            extract_commands: config.extract_commands ?? true,
            extract_entities: config.extract_entities ?? false,
        };

        if (JSON.stringify(newConfig) !== JSON.stringify(localConfig)) {
            setLocalConfig(newConfig);
        }
    }, [config]);

    useEffect(() => {
        if (JSON.stringify(localConfig) !== JSON.stringify(config)) {
            onChange(localConfig);
        }
    }, [localConfig]);

    const handleChange = (field: keyof TelegramParseNodeConfig, value: boolean) => {
        setLocalConfig((prev) => ({...prev, [field]: value}));
    };

    return (
        <div className="flex flex-col gap-4">
            <div className="flex flex-col gap-3">
                <h3 className="text-sm font-semibold text-gray-700">{t.nodeConfig.telegramParse.extractOptions}</h3>

                <label className="flex items-center gap-2 text-sm text-gray-700 cursor-pointer">
                    <input
                        type="checkbox"
                        checked={localConfig.extract_files ?? true}
                        onChange={(e) => handleChange('extract_files', e.target.checked)}
                        className="w-[18px] h-[18px] cursor-pointer"
                    />
                    <span>{t.nodeConfig.telegramParse.extractFiles}</span>
                    <span className="text-xs text-gray-500">
            {t.nodeConfig.telegramParse.extractFilesHint}
          </span>
                </label>

                <label className="flex items-center gap-2 text-sm text-gray-700 cursor-pointer">
                    <input
                        type="checkbox"
                        checked={localConfig.extract_commands ?? true}
                        onChange={(e) => handleChange('extract_commands', e.target.checked)}
                        className="w-[18px] h-[18px] cursor-pointer"
                    />
                    <span>{t.nodeConfig.telegramParse.extractCommands}</span>
                    <span className="text-xs text-gray-500">{t.nodeConfig.telegramParse.extractCommandsHint}</span>
                </label>

                <label className="flex items-center gap-2 text-sm text-gray-700 cursor-pointer">
                    <input
                        type="checkbox"
                        checked={localConfig.extract_entities ?? false}
                        onChange={(e) => handleChange('extract_entities', e.target.checked)}
                        className="w-[18px] h-[18px] cursor-pointer"
                    />
                    <span>{t.nodeConfig.telegramParse.extractEntities}</span>
                    <span className="text-xs text-gray-500">
            {t.nodeConfig.telegramParse.extractEntitiesHint}
          </span>
                </label>
            </div>

            <div className="p-3 bg-blue-50 border border-blue-200 rounded-md">
                <p className="text-xs text-blue-900">
                    {t.nodeConfig.telegramParse.infoText}
                </p>
            </div>
        </div>
    );
};

export default TelegramParseNodeConfigComponent;
