// mbflow-react/components/builder/EdgeConfigPanel.tsx
import React, {useEffect, useState} from 'react';
import {useDagStore} from '@/store/dagStore.ts';
import {VariableAutocomplete} from "@/components/builder";
import {ArrowRight, Check, Trash2, X, XCircle} from 'lucide-react';
import {Button} from '../ui';

export const EdgeConfigPanel: React.FC = () => {
    const {
        selectedEdgeId,
        edges,
        nodes,
        setSelectedEdgeId,
        updateEdge,
        deleteEdge,
    } = useDagStore();

    const selectedEdge = edges.find((e) => e.id === selectedEdgeId);
    const isOpen = !!selectedEdge;

    const [sourceHandle, setSourceHandle] = useState<string>('');
    const [condition, setCondition] = useState<string>('');

    useEffect(() => {
        if (selectedEdge) {
            setSourceHandle(selectedEdge.sourceHandle || '');
            setCondition((selectedEdge.data as any)?.condition || '');
        } else {
            setSourceHandle('');
            setCondition('');
        }
    }, [selectedEdge]);

    if (!selectedEdge) return null;

    const sourceNode = nodes.find((n) => n.id === selectedEdge.source);
    const targetNode = nodes.find((n) => n.id === selectedEdge.target);

    const sourceNodeLabel = sourceNode?.data?.label || selectedEdge.source;
    const targetNodeLabel = targetNode?.data?.label || selectedEdge.target;

    const isFromConditionalNode = sourceNode?.data?.type === 'conditional';

    const handleSave = () => {
        if (!selectedEdge) return;

        updateEdge(selectedEdge.id, {
            sourceHandle: sourceHandle || undefined,
            data: {
                ...selectedEdge.data,
                condition: condition || undefined,
            },
        });

        setSelectedEdgeId(null);
    };

    const handleDelete = () => {
        if (!selectedEdge) return;

        if (confirm('Are you sure you want to delete this edge?')) {
            deleteEdge(selectedEdge.id);
        }
    };

    const handleClose = () => {
        setSelectedEdgeId(null);
    };

    return (
        <>
            {/* Panel */}
            <div
                className={`fixed right-0 top-0 h-full w-96 bg-white dark:bg-slate-900 border-l border-slate-200 dark:border-slate-800 shadow-2xl z-50 transition-transform duration-300 ease-in-out transform ${
                    isOpen ? 'translate-x-0' : 'translate-x-full'
                }`}
            >
                <div className="flex flex-col h-full">
                    {/* Header */}
                    <div
                        className="flex items-center justify-between border-b border-slate-200 dark:border-slate-800 p-4 bg-slate-50/50 dark:bg-slate-900/50">
                        <div className="flex items-center gap-2">
                            <ArrowRight className="w-5 h-5 text-slate-700 dark:text-slate-300"/>
                            <h3 className="text-lg font-semibold text-slate-900 dark:text-slate-100">
                                Edge Configuration
                            </h3>
                        </div>
                        <Button
                            variant="ghost"
                            size="sm"
                            icon={<X className="w-5 h-5"/>}
                            onClick={handleClose}
                        />
                    </div>

                    {/* Content */}
                    <div className="flex-1 overflow-y-auto p-4 space-y-4">
                        {/* Edge Info */}
                        <div className="rounded-lg bg-slate-50 dark:bg-slate-950 p-3">
                            <div className="mb-2 text-sm font-medium text-slate-700 dark:text-slate-300">
                                Connection
                            </div>
                            <div className="flex items-center gap-2 text-sm">
                <span
                    className="rounded bg-blue-100 dark:bg-blue-900/30 px-2 py-1 font-mono text-blue-700 dark:text-blue-300">
                  {sourceNodeLabel}
                </span>
                                <ArrowRight className="w-4 h-4 text-slate-400 dark:text-slate-500"/>
                                <span
                                    className="rounded bg-green-100 dark:bg-green-900/30 px-2 py-1 font-mono text-green-700 dark:text-green-300">
                  {targetNodeLabel}
                </span>
                            </div>
                        </div>

                        {/* Source Handle (for conditional nodes) */}
                        {isFromConditionalNode && (
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700 dark:text-slate-300">
                                    Branch
                                </label>
                                <div className="flex gap-2">
                                    <button
                                        onClick={() => setSourceHandle('true')}
                                        className={`flex-1 rounded-lg border-2 px-4 py-2 text-sm font-medium transition-colors ${
                                            sourceHandle === 'true'
                                                ? 'border-green-500 bg-green-50 dark:bg-green-900/20 text-green-700 dark:text-green-400'
                                                : 'border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-950 text-slate-600 dark:text-slate-400 hover:border-green-300 dark:hover:border-green-700'
                                        }`}
                                    >
                                        <Check className="inline w-4 h-4 mr-1"/>
                                        True Branch
                                    </button>
                                    <button
                                        onClick={() => setSourceHandle('false')}
                                        className={`flex-1 rounded-lg border-2 px-4 py-2 text-sm font-medium transition-colors ${
                                            sourceHandle === 'false'
                                                ? 'border-red-500 bg-red-50 dark:bg-red-900/20 text-red-700 dark:text-red-400'
                                                : 'border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-950 text-slate-600 dark:text-slate-400 hover:border-red-300 dark:hover:border-red-700'
                                        }`}
                                    >
                                        <XCircle className="inline w-4 h-4 mr-1"/>
                                        False Branch
                                    </button>
                                </div>
                                <p className="text-xs text-slate-500 dark:text-slate-400">
                                    Select which branch of the conditional node this edge follows.
                                </p>
                            </div>
                        )}

                        {/* Condition Expression */}
                        <div className="space-y-2">
                            <label className="text-sm font-medium text-slate-700 dark:text-slate-300">
                                Condition Expression{' '}
                                <span className="text-slate-400 dark:text-slate-500">(optional)</span>
                            </label>
                            <VariableAutocomplete
                                type="textarea"
                                value={condition}
                                onChange={setCondition}
                                rows={3}
                                placeholder='output.status == "success"'
                                className="w-full px-3 py-2 text-sm bg-white dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-lg focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 outline-none transition-all resize-none text-slate-800 dark:text-slate-200 placeholder-slate-400 font-mono"
                            />
                            <p className="text-xs text-slate-500 dark:text-slate-400">
                                Use expr-lang syntax. Edge will only be followed if condition evaluates to
                                true.
                            </p>
                        </div>

                        {/* Info Box */}
                        <div
                            className="rounded-lg border border-blue-200 dark:border-blue-900/50 bg-blue-50 dark:bg-blue-900/20 p-3">
                            <h4 className="mb-2 text-sm font-semibold text-blue-800 dark:text-blue-300">
                                Condition Examples
                            </h4>
                            <ul className="space-y-1 text-xs text-blue-700 dark:text-blue-400">
                                <li>
                                    <code className="rounded bg-white dark:bg-blue-950/50 px-1 py-0.5">
                                        output.success == true
                                    </code>
                                </li>
                                <li>
                                    <code className="rounded bg-white dark:bg-blue-950/50 px-1 py-0.5">
                                        output.count &gt; 0
                                    </code>
                                </li>
                                <li>
                                    <code className="rounded bg-white dark:bg-blue-950/50 px-1 py-0.5">
                                        output.status == &quot;completed&quot;
                                    </code>
                                </li>
                            </ul>
                        </div>
                    </div>

                    {/* Footer */}
                    <div
                        className="space-y-2 border-t border-slate-200 dark:border-slate-800 p-4 bg-slate-50/50 dark:bg-slate-900/50">
                        <div className="flex gap-2">
                            <Button
                                variant="primary"
                                onClick={handleSave}
                                className="flex-1"
                            >
                                Save Changes
                            </Button>
                            <Button
                                variant="outline"
                                onClick={handleClose}
                            >
                                Cancel
                            </Button>
                        </div>
                        <Button
                            variant="danger"
                            fullWidth
                            icon={<Trash2 size={16} />}
                            onClick={handleDelete}
                        >
                            Delete Edge
                        </Button>
                    </div>
                </div>
            </div>

            {/* Backdrop */}
            {isOpen && (
                <div
                    className="fixed inset-0 z-40 bg-black/20 dark:bg-black/40 transition-opacity"
                    onClick={handleClose}
                />
            )}
        </>
    );
};

// mbflow-ui/src/components/workflow/EdgeConfigPanel.vue
<template>
  <div
    :class="[
      'edge-config-panel',
      'fixed right-0 top-0 h-full border-l border-gray-200 bg-white shadow-xl',
      'z-50 transition-transform duration-300 ease-in-out',
      isOpen ? 'translate-x-0' : 'translate-x-full',
    ]"
    style="width: 400px"
  >
    <div v-if="selectedEdge" class="flex h-full flex-col">
      <!-- Header -->
      <div
        class="flex items-center justify-between border-b border-gray-200 p-4"
      >
        <div class="flex items-center gap-2">
          <Icon icon="heroicons:arrow-long-right" class="size-5 text-gray-700" />
          <h3 class="text-lg font-semibold text-gray-900">
            Edge Configuration
          </h3>
        </div>
        <button
          class="rounded p-1 transition-colors hover:bg-gray-100"
          @click="closePanel"
        >
          <Icon icon="heroicons:x-mark" class="size-5 text-gray-500" />
        </button>
      </div>

      <!-- Form -->
      <div class="flex-1 space-y-4 overflow-y-auto p-4">
        <!-- Edge info -->
        <div class="rounded-lg bg-gray-50 p-3">
          <div class="mb-2 text-sm font-medium text-gray-700">Connection</div>
          <div class="flex items-center gap-2 text-sm">
            <span class="rounded bg-blue-100 px-2 py-1 font-mono text-blue-700">
              {{ sourceNodeLabel }}
            </span>
            <Icon icon="heroicons:arrow-right" class="size-4 text-gray-400" />
            <span class="rounded bg-green-100 px-2 py-1 font-mono text-green-700">
              {{ targetNodeLabel }}
            </span>
          </div>
        </div>

        <!-- Source Handle (for conditional nodes) -->
        <div v-if="isFromConditionalNode" class="space-y-2">
          <label class="text-sm font-medium text-gray-700">Branch</label>
          <div class="flex gap-2">
            <button
              :class="[
                'flex-1 rounded-lg border-2 px-4 py-2 text-sm font-medium transition-colors',
                sourceHandle === 'true'
                  ? 'border-green-500 bg-green-50 text-green-700'
                  : 'border-gray-200 bg-white text-gray-600 hover:border-green-300',
              ]"
              @click="sourceHandle = 'true'"
            >
              ✓ True Branch
            </button>
            <button
              :class="[
                'flex-1 rounded-lg border-2 px-4 py-2 text-sm font-medium transition-colors',
                sourceHandle === 'false'
                  ? 'border-red-500 bg-red-50 text-red-700'
                  : 'border-gray-200 bg-white text-gray-600 hover:border-red-300',
              ]"
              @click="sourceHandle = 'false'"
            >
              ✗ False Branch
            </button>
          </div>
          <p class="text-xs text-gray-500">
            Select which branch of the conditional node this edge follows.
          </p>
        </div>

        <!-- Custom Condition Expression -->
        <div class="space-y-2">
          <label class="text-sm font-medium text-gray-700">
            Condition Expression
            <span class="text-gray-400">(optional)</span>
          </label>
          <TemplateInput
            v-model="condition"
            height="80px"
            multiline
            placeholder="output.status == 'success'"
          />
          <p class="text-xs text-gray-500">
            Use expr-lang syntax. Edge will only be followed if condition evaluates to true.
          </p>
        </div>

        <!-- Info box -->
        <div class="rounded-lg border border-blue-200 bg-blue-50 p-3">
          <h4 class="mb-2 text-sm font-semibold text-blue-800">
            💡 Condition Examples
          </h4>
          <ul class="space-y-1 text-xs text-blue-700">
            <li><code class="rounded bg-white px-1">output.success == true</code></li>
            <li><code class="rounded bg-white px-1">output.count > 0</code></li>
            <li><code class="rounded bg-white px-1">output.status == "completed"</code></li>
          </ul>
        </div>
      </div>

      <!-- Footer -->
      <div class="space-y-2 border-t border-gray-200 p-4">
        <div class="flex gap-2">
          <Button variant="primary" class="flex-1" @click="saveConfig">
            Save Changes
          </Button>
          <Button variant="secondary" @click="closePanel"> Cancel </Button>
        </div>
        <Button variant="danger" class="w-full" @click="deleteEdge">
          Delete Edge
        </Button>
      </div>
    </div>
  </div>

  <!-- Backdrop -->
  <div
    v-if="isOpen"
    class="fixed inset-0 z-40 bg-black/20 transition-opacity"
    @click="closePanel"
  />
</template>

<script setup lang="ts">
import { computed, watch, ref } from "vue";
import { Icon } from "@iconify/vue";
import { toast } from "vue3-toastify";
import { useWorkflowStore } from "@/stores/workflow";
import Button from "@/components/ui/Button.vue";
import TemplateInput from "@/components/common/TemplateInput.vue";

const workflowStore = useWorkflowStore();
const emit = defineEmits(["save"]);

const selectedEdge = computed(() => workflowStore.selectedEdge);
const isOpen = computed(() => !!selectedEdge.value);

// Local form state
const sourceHandle = ref<string>("");
const condition = ref<string>("");

// Get source and target node labels
const sourceNodeLabel = computed(() => {
  if (!selectedEdge.value) return "";
  const node = workflowStore.nodes.find((n) => n.id === selectedEdge.value?.source);
  return node?.data?.label || selectedEdge.value.source;
});

const targetNodeLabel = computed(() => {
  if (!selectedEdge.value) return "";
  const node = workflowStore.nodes.find((n) => n.id === selectedEdge.value?.target);
  return node?.data?.label || selectedEdge.value.target;
});

// Check if source node is a conditional node
const isFromConditionalNode = computed(() => {
  if (!selectedEdge.value) return false;
  const node = workflowStore.nodes.find((n) => n.id === selectedEdge.value?.source);
  return node?.type === "conditional";
});

// Watch for edge selection changes
watch(
  selectedEdge,
  (edge) => {
    if (edge) {
      sourceHandle.value = edge.sourceHandle || "";
      condition.value = edge.data?.condition || "";
    } else {
      sourceHandle.value = "";
      condition.value = "";
    }
  },
  { immediate: true },
);

function closePanel() {
  workflowStore.selectEdge(null);
}

function saveConfig() {
  if (!selectedEdge.value) return;

  workflowStore.updateEdge(selectedEdge.value.id, {
    sourceHandle: sourceHandle.value || undefined,
    data: {
      ...selectedEdge.value.data,
      condition: condition.value || undefined,
    },
  });

  // Emit save event to trigger workflow persistence
  emit("save");

  toast.success("Edge configuration saved");
  closePanel();
}

function deleteEdge() {
  if (!selectedEdge.value) return;

  if (confirm("Are you sure you want to delete this edge?")) {
    workflowStore.removeEdge(selectedEdge.value.id);
    closePanel();
  }
}
</script>

<style scoped>
.edge-config-panel {
  max-width: 100vw;
}

code {
  font-family: "Monaco", "Menlo", monospace;
  font-size: 11px;
}
</style>
