// mbflow-ui/src/components/ui/Button.vue
<script setup lang="ts">
import { computed } from "vue";
import { cn } from "@/utils/cn";

interface Props {
  variant?: "primary" | "secondary" | "danger" | "ghost";
  size?: "sm" | "md" | "lg";
  disabled?: boolean;
  loading?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  variant: "primary",
  size: "md",
  disabled: false,
  loading: false,
});

const classes = computed(() =>
  cn(
    "inline-flex items-center justify-center rounded-md font-medium transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none",
    {
      "bg-blue-600 text-white hover:bg-blue-700 focus:ring-blue-500":
        props.variant === "primary",
      "bg-gray-200 text-gray-900 hover:bg-gray-300 focus:ring-gray-500":
        props.variant === "secondary",
      "bg-red-600 text-white hover:bg-red-700 focus:ring-red-500":
        props.variant === "danger",
      "hover:bg-gray-100 focus:ring-gray-500": props.variant === "ghost",
    },
    {
      "px-3 py-1.5 text-sm": props.size === "sm",
      "px-4 py-2 text-base": props.size === "md",
      "px-6 py-3 text-lg": props.size === "lg",
    },
  ),
);
</script>

<template>
  <button :class="classes" :disabled="disabled || loading">
    <span v-if="loading" class="mr-2">
      <svg
        class="size-4 animate-spin"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
      >
        <circle
          class="opacity-25"
          cx="12"
          cy="12"
          r="10"
          stroke="currentColor"
          stroke-width="4"
        ></circle>
        <path
          class="opacity-75"
          fill="currentColor"
          d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
        ></path>
      </svg>
    </span>
    <slot />
  </button>
</template>

// ui/components/ui/Button.tsx
import React from 'react';
import {Loader2} from 'lucide-react';

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
    variant?: 'primary' | 'secondary' | 'danger' | 'ghost' | 'outline';
    size?: 'sm' | 'md' | 'lg';
    loading?: boolean;
    icon?: React.ReactNode;
    iconPosition?: 'left' | 'right';
    textPosition?: 'left' | 'right' | 'center';
    fullWidth?: boolean;
    children?: React.ReactNode;
}

const cn = (...classes: (string | undefined | null | false)[]): string => {
    return classes.filter(Boolean).join(' ');
};

const variantStyles: Record<string, string> = {
    primary: 'bg-blue-600 hover:bg-blue-700 text-white disabled:bg-blue-400',
    secondary: 'bg-gray-200 hover:bg-gray-300 text-gray-800 disabled:bg-gray-100',
    danger: 'bg-red-600 hover:bg-red-700 text-white disabled:bg-red-400',
    ghost: 'hover:bg-gray-100 text-gray-700 dark:hover:bg-gray-800 dark:text-gray-200 disabled:hover:bg-transparent',
    outline: 'border border-gray-300 dark:border-gray-600 hover:bg-gray-50 dark:hover:bg-gray-800 text-gray-700 dark:text-gray-200 disabled:hover:bg-transparent',
};

const sizeStyles: Record<string, string> = {
    sm: 'px-2 py-1 text-sm',
    md: 'px-4 py-2 text-base',
    lg: 'px-6 py-3 text-lg',
};

export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
    (
        {
            variant = 'primary',
            size = 'md',
            loading = false,
            icon,
            iconPosition = 'left',
            textPosition = 'center',
            fullWidth = false,
            disabled = false,
            children,
            className,
            ...props
        },
        ref
    ) => {
        const isDisabled = disabled || loading;

        const baseStyles =
            'inline-flex items-center justify-center rounded-lg font-medium transition-all focus:outline-none focus:ring-2 focus:ring-offset-2 dark:focus:ring-offset-slate-900 disabled:cursor-not-allowed disabled:opacity-50';

        const widthStyles = fullWidth ? 'w-full' : '';

        const variantClass = variantStyles[variant] || variantStyles.primary;
        const sizeClass = sizeStyles[size] || sizeStyles.md;

        const focusRingColor = {
            primary: 'focus:ring-blue-500',
            secondary: 'focus:ring-gray-400',
            danger: 'focus:ring-red-500',
            ghost: 'focus:ring-gray-400',
            outline: 'focus:ring-gray-400',
        }[variant];

        const buttonClass = cn(
            baseStyles,
            variantClass,
            sizeClass,
            widthStyles,
            focusRingColor,
            className
        );

        const renderContent = () => {
            if (loading) {
                return (
                    <div className="flex items-center gap-2">
                        <Loader2 size={16} className="animate-spin"/>
                        {children}
                    </div>
                );
            }

            if (!icon) {
                return children;
            }

            if (iconPosition === 'left') {
                return (
                    <div className="flex items-center gap-2">
                        <span className="flex-shrink-0">{icon}</span>
                        {children}
                    </div>
                );
            }

            return (
                <div className="flex items-center gap-2">
                    {children}
                    <span className="flex-shrink-0">{icon}</span>
                </div>
            );
        };

        return (
            <button
                ref={ref}
                disabled={isDisabled}
                className={buttonClass}
                {...props}
            >
                {renderContent()}
            </button>
        );
    }
);

Button.displayName = 'Button';
