// mbflow-ui/src/components/nodes/config/ConditionalNodeConfig.vue
<template>
  <div class="conditional-node-config">
    <div class="form-group">
      <label class="label">Condition Expression</label>
      <TemplateInput
        v-model="localConfig.condition"
        height="100px"
        :node-id="nodeId"
        multiline
        placeholder="{{input.value}} > 0"
      />
      <p class="mt-1 text-xs text-gray-500">
        Use expr-lang syntax to evaluate conditions. Returns true/false.
      </p>
    </div>

    <div class="info-box">
      <h4 class="info-title">💡 Expression Examples</h4>
      <ul class="examples-list">
        <li><code v-pre>{{input.value}} > 100</code> - Numeric comparison</li>
        <li><code v-pre>{{input.status}} == "active"</code> - String equality</li>
        <li>
          <code v-pre>{{input.count}} > 0 && {{input.enabled}}</code> - Multiple
          conditions
        </li>
        <li>
          <code v-pre>len({{input.items}}) > 5</code> - Array length check
        </li>
      </ul>
    </div>

    <div class="info-box info-box-warning">
      <h4 class="info-title">⚠️ Important Notes</h4>
      <ul class="notes-list">
        <li>
          <strong>True branch:</strong> Nodes connected via edge labeled "true"
          or default first edge
        </li>
        <li>
          <strong>False branch:</strong> Nodes connected via edge labeled
          "false" or second edge
        </li>
        <li>
          If condition evaluates to true, only the true branch will execute
        </li>
        <li>Templates like <code v-pre>{{input.X}}</code> are resolved before evaluation</li>
      </ul>
    </div>

    <div class="reference-box">
      <h4 class="reference-title">📚 Supported Operators</h4>
      <div class="operators-grid">
        <div class="operator-category">
          <h5>Comparison</h5>
          <code>==, !=, >, <, >=, <=</code>
        </div>
        <div class="operator-category">
          <h5>Logical</h5>
          <code>&&, ||, !</code>
        </div>
        <div class="operator-category">
          <h5>Arithmetic</h5>
          <code>+, -, *, /, %</code>
        </div>
        <div class="operator-category">
          <h5>Functions</h5>
          <code>len(), contains(), matches()</code>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from "vue";
import type { ConditionalNodeConfig } from "@/types/nodes";
import TemplateInput from "@/components/common/TemplateInput.vue";

interface Props {
  config: ConditionalNodeConfig;
  nodeId?: string;
}

const props = defineProps<Props>();

const emit = defineEmits<{
  (e: "update:config", config: ConditionalNodeConfig): void;
}>();

const localConfig = ref<ConditionalNodeConfig>({
  condition: "{{input.value}} > 0",
  ...(props.config || {}),
});

// Watch for external config changes
watch(
  () => props.config,
  (newConfig) => {
    if (JSON.stringify(newConfig) !== JSON.stringify(localConfig.value)) {
      localConfig.value = { ...newConfig };
    }
  },
  { deep: true }
);

// Emit changes
watch(
  localConfig,
  (newConfig) => {
    emit("update:config", newConfig);
  },
  { deep: true }
);
</script>

<style scoped>
.conditional-node-config {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.label {
  font-size: 13px;
  font-weight: 600;
  color: #374151;
}

.info-box {
  padding: 16px;
  background-color: #f0f9ff;
  border: 1px solid #bae6fd;
  border-radius: 8px;
}

.info-box-warning {
  background-color: #fef3c7;
  border-color: #fde68a;
}

.info-title {
  font-size: 13px;
  font-weight: 700;
  color: #0c4a6e;
  margin: 0 0 12px 0;
}

.info-box-warning .info-title {
  color: #92400e;
}

.examples-list,
.notes-list {
  margin: 0;
  padding-left: 20px;
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.examples-list li,
.notes-list li {
  font-size: 12px;
  color: #374151;
  line-height: 1.5;
}

code {
  background-color: #ffffff;
  padding: 2px 6px;
  border-radius: 3px;
  font-family: "Monaco", "Menlo", monospace;
  font-size: 11px;
  color: #0369a1;
  border: 1px solid #e0f2fe;
}

.reference-box {
  padding: 16px;
  background-color: #f9fafb;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
}

.reference-title {
  font-size: 13px;
  font-weight: 700;
  color: #374151;
  margin: 0 0 12px 0;
}

.operators-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 12px;
}

.operator-category h5 {
  font-size: 11px;
  font-weight: 600;
  color: #6b7280;
  margin: 0 0 4px 0;
  text-transform: uppercase;
}

.operator-category code {
  display: block;
  font-size: 12px;
}
</style>

// mbflow-react/components/nodes/config/ConditionalNodeConfig.tsx
/**
 * ConditionalNodeConfig - React component for configuring conditional nodes
 *
 * Ported from: /mbflow-ui/src/components/nodes/config/ConditionalNodeConfig.vue
 *
 * Features:
 * - Condition expression editor with template variable support
 * - Expression examples with different use cases
 * - Important notes about branch execution
 * - Supported operators reference
 *
 * Usage:
 * ```tsx
 * <ConditionalNodeConfig
 *   config={conditionalConfig}
 *   nodeId="node-123"
 *   onChange={(newConfig) => console.log(newConfig)}
 * />
 * ```
 */

import React, {useEffect, useState} from 'react';
import {ConditionalNodeConfig} from '@/types/nodeConfigs.ts';
import {VariableAutocomplete} from '@/components';

interface ConditionalNodeConfigProps {
    config: ConditionalNodeConfig;
    nodeId?: string;
    onChange: (config: ConditionalNodeConfig) => void;
}

export const ConditionalNodeConfigComponent: React.FC<ConditionalNodeConfigProps> = ({
                                                                                         config,
                                                                                         nodeId,
                                                                                         onChange,
                                                                                     }) => {
    const [localConfig, setLocalConfig] = useState<ConditionalNodeConfig>({
        ...config,
        condition: config.condition || '{{input.value}} > 0',
    });

    useEffect(() => {
        const newConfig = {
            ...config,
            condition: config.condition || '{{input.value}} > 0',
        };

        if (JSON.stringify(newConfig) !== JSON.stringify(localConfig)) {
            setLocalConfig(newConfig);
        }
    }, [config]);

    useEffect(() => {
        if (JSON.stringify(localConfig) !== JSON.stringify(config)) {
            onChange(localConfig);
        }
    }, [localConfig]);

    const handleConditionChange = (condition: string) => {
        setLocalConfig((prev) => ({...prev, condition}));
    };

    return (
        <div className="flex flex-col gap-4">
            {/* Condition Expression */}
            <div className="flex flex-col gap-1.5">
                <label className="text-[13px] font-semibold text-slate-700 dark:text-slate-300">
                    Condition Expression
                </label>
                <VariableAutocomplete
                    value={localConfig.condition || ''}
                    onChange={handleConditionChange}
                    placeholder="{{input.value}} > 0"
                    type="textarea"
                    rows={4}
                    className="w-full px-3 py-2 border border-slate-200 dark:border-slate-700 rounded-lg text-sm font-mono bg-white dark:bg-slate-900 text-slate-900 dark:text-slate-100 focus:outline-none focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400 focus:border-transparent resize-vertical min-h-[80px]"
                />
                <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
                    Use expr-lang syntax to evaluate conditions. Returns true/false.
                </p>
            </div>

            {/* Expression Examples */}
            <div className="p-4 bg-blue-50 dark:bg-blue-950/20 border border-blue-200 dark:border-blue-800 rounded-lg">
                <h4 className="text-[13px] font-bold text-blue-900 dark:text-blue-100 mb-3">
                    💡 Expression Examples
                </h4>
                <ul className="flex flex-col gap-2 pl-5 list-disc">
                    <li className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed">
                        <code
                            className="bg-white dark:bg-slate-800 px-1.5 py-0.5 rounded border border-blue-100 dark:border-blue-900 font-mono text-[11px] text-blue-700 dark:text-blue-300">
                            {'{{input.value}} > 100'}
                        </code>
                        {' - Numeric comparison'}
                    </li>
                    <li className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed">
                        <code
                            className="bg-white dark:bg-slate-800 px-1.5 py-0.5 rounded border border-blue-100 dark:border-blue-900 font-mono text-[11px] text-blue-700 dark:text-blue-300">
                            {'{{input.status}} == "active"'}
                        </code>
                        {' - String equality'}
                    </li>
                    <li className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed">
                        <code
                            className="bg-white dark:bg-slate-800 px-1.5 py-0.5 rounded border border-blue-100 dark:border-blue-900 font-mono text-[11px] text-blue-700 dark:text-blue-300">
                            {'{{input.count}} > 0 && {{input.enabled}}'}
                        </code>
                        {' - Multiple conditions'}
                    </li>
                    <li className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed">
                        <code
                            className="bg-white dark:bg-slate-800 px-1.5 py-0.5 rounded border border-blue-100 dark:border-blue-900 font-mono text-[11px] text-blue-700 dark:text-blue-300">
                            {'len({{input.items}}) > 5'}
                        </code>
                        {' - Array length check'}
                    </li>
                </ul>
            </div>

            {/* Important Notes */}
            <div
                className="p-4 bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800 rounded-lg">
                <h4 className="text-[13px] font-bold text-amber-900 dark:text-amber-100 mb-3">
                    ⚠️ Important Notes
                </h4>
                <ul className="flex flex-col gap-2 pl-5 list-disc">
                    <li className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed">
                        <strong>True branch:</strong> Nodes connected via edge labeled "true" or default first edge
                    </li>
                    <li className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed">
                        <strong>False branch:</strong> Nodes connected via edge labeled "false" or second edge
                    </li>
                    <li className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed">
                        If condition evaluates to true, only the true branch will execute
                    </li>
                    <li className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed">
                        Templates like{' '}
                        <code
                            className="bg-white dark:bg-slate-800 px-1.5 py-0.5 rounded border border-amber-100 dark:border-amber-900 font-mono text-[11px] text-amber-700 dark:text-amber-300">
                            {'{{input.X}}'}
                        </code>
                        {' are resolved before evaluation'}
                    </li>
                </ul>
            </div>

            {/* Supported Operators */}
            <div className="p-4 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-lg">
                <h4 className="text-[13px] font-bold text-slate-700 dark:text-slate-300 mb-3">
                    📚 Supported Operators
                </h4>
                <div className="grid grid-cols-2 gap-3">
                    <div>
                        <h5 className="text-[11px] font-semibold text-slate-500 dark:text-slate-400 uppercase mb-1">
                            Comparison
                        </h5>
                        <code
                            className="block text-xs bg-white dark:bg-slate-800 px-2 py-1 rounded border border-slate-200 dark:border-slate-700 font-mono text-slate-700 dark:text-slate-300">
                            ==, !=, &gt;, &lt;, &gt;=, &lt;=
                        </code>
                    </div>
                    <div>
                        <h5 className="text-[11px] font-semibold text-slate-500 dark:text-slate-400 uppercase mb-1">
                            Logical
                        </h5>
                        <code
                            className="block text-xs bg-white dark:bg-slate-800 px-2 py-1 rounded border border-slate-200 dark:border-slate-700 font-mono text-slate-700 dark:text-slate-300">
                            &amp;&amp;, ||, !
                        </code>
                    </div>
                    <div>
                        <h5 className="text-[11px] font-semibold text-slate-500 dark:text-slate-400 uppercase mb-1">
                            Arithmetic
                        </h5>
                        <code
                            className="block text-xs bg-white dark:bg-slate-800 px-2 py-1 rounded border border-slate-200 dark:border-slate-700 font-mono text-slate-700 dark:text-slate-300">
                            +, -, *, /, %
                        </code>
                    </div>
                    <div>
                        <h5 className="text-[11px] font-semibold text-slate-500 dark:text-slate-400 uppercase mb-1">
                            Functions
                        </h5>
                        <code
                            className="block text-xs bg-white dark:bg-slate-800 px-2 py-1 rounded border border-slate-200 dark:border-slate-700 font-mono text-slate-700 dark:text-slate-300">
                            len(), contains(), matches()
                        </code>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ConditionalNodeConfigComponent;
