// mbflow-ui/src/components/nodes/config/HTTPNodeConfig.vue
<template>
  <div class="http-node-config">
    <div class="form-group">
      <label class="label">HTTP Method</label>
      <select v-model="localConfig.method" class="select-field">
        <option v-for="method in HTTP_METHODS" :key="method" :value="method">
          {{ method }}
        </option>
      </select>
    </div>

    <div class="form-group">
      <label class="label">URL</label>
      <TemplateInput
        v-model="localConfig.url"
        placeholder="https://api.example.com/endpoint"
        :node-id="nodeId"
      />
    </div>

    <div class="form-group">
      <label class="label">Headers</label>
      <KeyValueEditor
        v-model="localConfig.headers"
        :node-id="nodeId"
        placeholder-key="Content-Type"
        placeholder-value="application/json"
      />
    </div>

    <div
      v-if="['POST', 'PUT', 'PATCH'].includes(localConfig.method)"
      class="form-group"
    >
      <label class="label">Body</label>
      <MonacoEditor
        v-model="localConfig.body"
        language="json"
        height="150px"
        :node-id="nodeId"
      />
    </div>

    <div class="form-group">
      <label class="label">Timeout (seconds)</label>
      <input
        v-model.number="localConfig.timeout_seconds"
        type="number"
        min="1"
        max="300"
        class="input-field"
      />
    </div>

    <div class="form-group">
      <label class="label">Retry Count</label>
      <input
        v-model.number="localConfig.retry_count"
        type="number"
        min="0"
        max="10"
        class="input-field"
      />
    </div>

    <div class="form-group">
      <label class="checkbox-label">
        <input
          v-model="localConfig.follow_redirects"
          type="checkbox"
          class="checkbox-field"
        />
        Follow Redirects
      </label>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from "vue";
import type { HTTPNodeConfig } from "@/types/nodes";
import { HTTP_METHODS } from "@/types/nodes";
import TemplateInput from "@/components/common/TemplateInput.vue";
import MonacoEditor from "@/components/common/MonacoEditor.vue";
import KeyValueEditor from "@/components/common/KeyValueEditor.vue";

interface Props {
  config: HTTPNodeConfig;
  nodeId?: string;
}

const props = defineProps<Props>();

const emit = defineEmits<{
  (e: "update:config", config: HTTPNodeConfig): void;
}>();

const localConfig = ref<HTTPNodeConfig>({ ...props.config });

// Watch for external config changes
watch(
  () => props.config,
  (newConfig) => {
    localConfig.value = { ...newConfig };
  },
  { deep: true }
);

// Emit changes
watch(
  localConfig,
  (newConfig) => {
    emit("update:config", newConfig);
  },
  { deep: true }
);
</script>

<style scoped>
.http-node-config {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.label {
  font-size: 13px;
  font-weight: 600;
  color: #374151;
}

.input-field,
.select-field {
  width: 100%;
  padding: 8px 12px;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  font-size: 14px;
  transition: border-color 0.2s;
}

.input-field:focus,
.select-field:focus {
  outline: none;
  border-color: #3b82f6;
  box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
}

.checkbox-label {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 14px;
  color: #374151;
  cursor: pointer;
}

.checkbox-field {
  width: 18px;
  height: 18px;
  cursor: pointer;
}
</style>

// mbflow-react/components/nodes/config/HTTPNodeConfig.tsx
/**
 * HTTPNodeConfig - React component for configuring HTTP request nodes
 *
 * Ported from: /mbflow-ui/src/components/nodes/config/HTTPNodeConfig.vue
 *
 * Features:
 * - HTTP method selection (GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS)
 * - URL input with template variable support
 * - Key-value header editor (simple implementation)
 * - JSON body editor (textarea for POST/PUT/PATCH methods)
 * - Timeout and retry configuration
 * - Follow redirects toggle
 *
 * Usage:
 * ```tsx
 * <HTTPNodeConfig
 *   config={httpConfig}
 *   nodeId="node-123"
 *   onChange={(newConfig) => console.log(newConfig)}
 * />
 * ```
 */

import React, {useEffect, useState} from "react";
import {HTTP_METHODS, HTTPNodeConfig} from "@/types/nodeConfigs.ts";
import {Button} from '@/components/ui';

interface HTTPNodeConfigProps {
    config: HTTPNodeConfig;
    nodeId?: string;
    onChange: (config: HTTPNodeConfig) => void;
}

export const HTTPNodeConfigComponent: React.FC<HTTPNodeConfigProps> = ({
                                                                           config,
                                                                           nodeId,
                                                                           onChange,
                                                                       }) => {
    const [localConfig, setLocalConfig] = useState<HTTPNodeConfig>({
        ...config,
        headers: config.headers ?? {},
        body: config.body ?? "",
    });

    useEffect(() => {
        const newConfig = {
            ...config,
            headers: config.headers ?? {},
            body: config.body ?? "",
        };

        if (JSON.stringify(newConfig) !== JSON.stringify(localConfig)) {
            setLocalConfig(newConfig);
        }
    }, [config]);

    useEffect(() => {
        if (JSON.stringify(localConfig) !== JSON.stringify(config)) {
            onChange(localConfig);
        }
    }, [localConfig]);

    const updateConfig = (updates: Partial<HTTPNodeConfig>) => {
        setLocalConfig((prev) => ({...prev, ...updates}));
    };

    const shouldShowBody = ["POST", "PUT", "PATCH"].includes(localConfig.method);

    return (
        <div className="flex flex-col gap-4">
            <div className="flex flex-col gap-1.5">
                <label className="text-sm font-semibold text-gray-700">
                    HTTP Method
                </label>
                <select
                    value={localConfig.method}
                    onChange={(e) =>
                        updateConfig({
                            method: e.target.value as HTTPNodeConfig["method"],
                        })
                    }
                    className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm transition-colors focus:outline-none focus:border-blue-500 focus:ring-3 focus:ring-blue-100"
                >
                    {HTTP_METHODS.map((method) => (
                        <option key={method} value={method}>
                            {method}
                        </option>
                    ))}
                </select>
            </div>

            <div className="flex flex-col gap-1.5">
                <label className="text-sm font-semibold text-gray-700">URL</label>
                <input
                    type="text"
                    value={localConfig.url}
                    onChange={(e) => updateConfig({url: e.target.value})}
                    placeholder="https://api.example.com/endpoint"
                    className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm transition-colors focus:outline-none focus:border-blue-500 focus:ring-3 focus:ring-blue-100"
                />
                <span className="text-xs text-gray-500">
          Supports template variables: {`{{env.API_KEY}}, {{node.previous.result}}`}
        </span>
            </div>

            <div className="flex flex-col gap-1.5">
                <label className="text-sm font-semibold text-gray-700">Headers</label>
                <div className="space-y-2">
                    {Object.entries(localConfig.headers || {}).map(([key, value], index) => (
                        <div key={index} className="flex gap-2">
                            <input
                                type="text"
                                value={key}
                                onChange={(e) => {
                                    const newHeaders = {...localConfig.headers};
                                    delete newHeaders[key];
                                    newHeaders[e.target.value] = value;
                                    updateConfig({headers: newHeaders});
                                }}
                                placeholder="Content-Type"
                                className="flex-1 px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:border-blue-500 focus:ring-3 focus:ring-blue-100"
                            />
                            <input
                                type="text"
                                value={value}
                                onChange={(e) => {
                                    const newHeaders = {...localConfig.headers};
                                    newHeaders[key] = e.target.value;
                                    updateConfig({headers: newHeaders});
                                }}
                                placeholder="application/json"
                                className="flex-1 px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:border-blue-500 focus:ring-3 focus:ring-blue-100"
                            />
                            <Button
                                onClick={() => {
                                    const newHeaders = {...localConfig.headers};
                                    delete newHeaders[key];
                                    updateConfig({headers: newHeaders});
                                }}
                                variant="danger"
                                size="sm"
                                title="Remove header"
                            >
                                ×
                            </Button>
                        </div>
                    ))}
                    <Button
                        onClick={() => {
                            const newHeaders = {...localConfig.headers};
                            let counter = 1;
                            while (newHeaders[`header${counter}`]) {
                                counter++;
                            }
                            newHeaders[`header${counter}`] = "";
                            updateConfig({headers: newHeaders});
                        }}
                        variant="outline"
                        size="sm"
                        fullWidth
                    >
                        + Add Header
                    </Button>
                </div>
            </div>

            {shouldShowBody && (
                <div className="flex flex-col gap-1.5">
                    <label className="text-sm font-semibold text-gray-700">Body</label>
                    <textarea
                        value={localConfig.body || ""}
                        onChange={(e) => updateConfig({body: e.target.value})}
                        placeholder='{"key": "value"}'
                        rows={6}
                        className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm font-mono transition-colors focus:outline-none focus:border-blue-500 focus:ring-3 focus:ring-blue-100 resize-y"
                    />
                    <span className="text-xs text-gray-500">
            JSON format. Supports template variables.
          </span>
                </div>
            )}

            <div className="flex flex-col gap-1.5">
                <label className="text-sm font-semibold text-gray-700">
                    Timeout (seconds)
                </label>
                <input
                    type="number"
                    value={localConfig.timeout_seconds ?? 30}
                    onChange={(e) =>
                        updateConfig({timeout_seconds: Number(e.target.value)})
                    }
                    min={1}
                    max={300}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm transition-colors focus:outline-none focus:border-blue-500 focus:ring-3 focus:ring-blue-100"
                />
            </div>

            <div className="flex flex-col gap-1.5">
                <label className="text-sm font-semibold text-gray-700">
                    Retry Count
                </label>
                <input
                    type="number"
                    value={localConfig.retry_count ?? 0}
                    onChange={(e) =>
                        updateConfig({retry_count: Number(e.target.value)})
                    }
                    min={0}
                    max={10}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm transition-colors focus:outline-none focus:border-blue-500 focus:ring-3 focus:ring-blue-100"
                />
            </div>

            <div className="flex flex-col gap-1.5">
                <label className="flex items-center gap-2 text-sm text-gray-700 cursor-pointer">
                    <input
                        type="checkbox"
                        checked={localConfig.follow_redirects ?? true}
                        onChange={(e) =>
                            updateConfig({follow_redirects: e.target.checked})
                        }
                        className="w-[18px] h-[18px] cursor-pointer"
                    />
                    Follow Redirects
                </label>
            </div>
        </div>
    );
};

export default HTTPNodeConfigComponent;
